### ISSUE TITLE
EPIC [wins] Support upgrading wins version / config on Windows hosts

### ISSUE THREAD

**Issue by aiyengar2** [rancher/wins#22]
This issue is an Epic that tracks several other issues around supporting wins upgrades to the version or configuration across all hosts in a Windows cluster.

### Tasks
- [x] Support `.\wins.exe up[grade]` (https://github.com/rancher/wins/issues/23)
- [x] Create build images for wins (https://github.com/rancher/wins/issues/24)
- [x] Add Helm chart for wins upgrade (https://github.com/rancher/wins/issues/20)
- [x] Expose Helm chart on Rancher Helm repository (https://github.com/rancher/rancher/issues/31504)

### Note

Related to https://github.com/rancher/rancher/issues/28327, which requires wins upgrades across Windows hosts in the cluster to be able to be deployed

**Comment by thehejik** [comment]
All tested in Monitoring+v2+Windows+Support document. Closing.
